### ISSUE TITLE
Error on 'yarn tests:watch'

### ISSUE THREAD

**Issue by drockyy** [sysgears/apollo-universal-starter-kit#854]
Starting yarn tests:watch following error appears:

> lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run tests:watch
lerna ERR! (node:19568) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
lerna ERR!
lerna ERR! C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\mocha-webpack\lib\webpack\InjectChangedFilesPlugin.js:35
lerna ERR!   return modules.filter(isBuilt).map(getId).reduce(setTrue, {});
lerna ERR!                  ^
lerna ERR! TypeError: Cannot read property 'filter' of undefined
lerna ERR!     at getAffectedFiles (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\mocha-webpack\lib\webpack\InjectChangedFilesPlugin.js:35:18)
lerna ERR!     at C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\mocha-webpack\lib\webpack\InjectChangedFilesPlugin.js:83:33
lerna ERR!     at Array.forEach (<anonymous>)
lerna ERR!     at C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\mocha-webpack\lib\webpack\InjectChangedFilesPlugin.js:81:18
lerna ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:7:1)
lerna ERR!     at AsyncSeriesHook.lazyCompileHook (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\Hook.js:154:20)
lerna ERR!     at hooks.additionalAssets.callAsync.err (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compilation.js:1281:36)
lerna ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
lerna ERR!     at AsyncSeriesHook.lazyCompileHook (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\Hook.js:154:20)
lerna ERR!     at hooks.optimizeTree.callAsync.err (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compilation.js:1277:32)
lerna ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
lerna ERR!     at AsyncSeriesHook.lazyCompileHook (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\Hook.js:154:20)
lerna ERR!     at Compilation.seal (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compilation.js:1214:27)
lerna ERR!     at hooks.make.callAsync.err (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compiler.js:547:17)
lerna ERR!     at _err0 (eval at create (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:11:1)
lerna ERR!     at _addModuleChain (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compilation.js:1065:12)
lerna ERR!     at processModuleDependencies.err (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compilation.js:981:9)
lerna ERR!     at _combinedTickCallback (internal/process/next_tick.js:131:7)
lerna ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
lerna ERR! error Command failed with exit code 1.
lerna ERR!

Environment: Windows 10

To reproduce this error:
`git clone https://github.com/sysgears/apollo-universal-starter-kit`
`yarn`
`yarn seed`
`yarn build`
`yarn tests:watch`

**Comment by vlasenko** [comment]
@drockyy Thank you, reproduces under Linux as well. Looks like recent webpack versions had breaking API changes and `mocha-webpack@0.7.0` has stopped working. This has happened on some very recent webpack version. `mocha-webpack@0.7.0` has worked flawlessly for us with Webpack 1, 2, 3, and most of 4.x versions. The more recent `mocha-webpack` versions were very buggy every time we tried them...

**Comment by vlasenko** [comment]
@drockyy I have pushed the probable fix into `master` - upgraded `mocha-webpack` to latest version and make some adjustment of command-line arguments passed to `mocha-webpack`. Could you check is latest code in `master` works for you?

**Comment by drockyy** [comment]
@vlasenko I have tried it again, but it still does not work. It appears the same error like before. It seems we have to wait for new updates from `mocha-webpack`.

**Comment by vlasenko** [comment]
@drockyy Have you run `yarn` after pulling out the latest master source code?

**Comment by drockyy** [comment]
@vlasenko Yes, the complete routine, which I have described above

**Comment by vlasenko** [comment]
@drockyy What is the exact error message, because it cannot be the same, I have upgraded `mocha-webpack` to version `2.0.0-beta.0` in `master`, so error message obviously cannot be the same, at least line numbers in stack trace will be different

**Comment by drockyy** [comment]
> lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run tests:watch
lerna ERR! (node:16920) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
lerna ERR!
lerna ERR! C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\mocha-webpack\lib\webpack\InjectChangedFilesPlugin.js:35
lerna ERR!   return modules.filter(isBuilt).map(getId).reduce(setTrue, {});
lerna ERR!                  ^
lerna ERR! TypeError: Cannot read property 'filter' of undefined
lerna ERR!     at getAffectedFiles (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\mocha-webpack\lib\webpack\InjectChangedFilesPlugin.js:35:18)
lerna ERR!     at C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\mocha-webpack\lib\webpack\InjectChangedFilesPlugin.js:83:33
lerna ERR!     at Array.forEach (<anonymous>)
lerna ERR!     at C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\mocha-webpack\lib\webpack\InjectChangedFilesPlugin.js:81:18
lerna ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:7:1)
lerna ERR!     at AsyncSeriesHook.lazyCompileHook (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\Hook.js:154:20)
lerna ERR!     at hooks.additionalAssets.callAsync.err (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compilation.js:1281:36)
lerna ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
lerna ERR!     at AsyncSeriesHook.lazyCompileHook (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\Hook.js:154:20)
lerna ERR!     at hooks.optimizeTree.callAsync.err (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compilation.js:1277:32)
lerna ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
lerna ERR!     at AsyncSeriesHook.lazyCompileHook (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\Hook.js:154:20)
lerna ERR!     at Compilation.seal (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compilation.js:1214:27)
lerna ERR!     at hooks.make.callAsync.err (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compiler.js:547:17)
lerna ERR!     at _err0 (eval at create (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:11:1)
lerna ERR!     at _addModuleChain (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compilation.js:1065:12)
lerna ERR!     at processModuleDependencies.err (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\webpack\lib\Compilation.js:981:9)
lerna ERR!     at _combinedTickCallback (internal/process/next_tick.js:131:7)
lerna ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
lerna ERR! error Command failed with exit code 1.
lerna ERR!
lerna ERR! $ cross-env NODE_ENV=test PORT=7070 spin test -t 10000 --full-trace --watch "src/**/*.spec.*"
lerna ERR! spin info Running C:\Users\..\Desktop\apollo-universal-starter-kit\packages\mobile\node_modules\.bin\mocha-webpack.cmd --webpack-config C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\spinjs\webpack.config.js --include raf/polyfill -t 10000 --full-trace --watch src/**/*.spec.*
lerna ERR! Starting type checking service...
lerna ERR! Using 1 worker with 2048MB memory limit
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\Users\..\Desktop\apollo-universal-starter-kit\node_modules\lerna\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>

**Comment by drockyy** [comment]
I got this error message two times behind each other, after `yarn`, `yarn seed`, `yarn build` and `yarn tests:watch`

**Comment by vlasenko** [comment]
@drockyy `mocha-webpack@2.0.0-beta.0` doesn't have file `webpack\lib\webpack\InjectChangedFilesPlugin.js`, so you have wrong dependencies, double check that you have version 2.0.0-beta.0 in `C:\Users..\Desktop\apollo-universal-starter-kit\node_modules\mocha-webpack\package.json`

**Comment by drockyy** [comment]
@vlasenko Thanks a lot, now it works. After cleaning all dependencies and chaches I have gotten version 2.0.0-beta.0 of mocha-webpack.
But 1 Error appears in a test:

> server:   1 failing
server:   1) "before all" hook:
server:      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
server:       at Hook.Runnable._timeoutError (C:\Users\Dennis\Desktop\apollo-universal-starter-kit\node_modules\mocha\lib\runnable.js:440:10)
server:       at done (C:\Users\Dennis\Desktop\apollo-universal-starter-kit\node_modules\mocha\lib\runnable.js:317:18)
server:       at C:\Users\Dennis\Desktop\apollo-universal-starter-kit\node_modules\mocha\lib\runnable.js:377:11
server:       at <anonymous>
server:       at process._tickCallback (internal/process/next_tick.js:188:7)
server:  MOCHA  Tests completed with 1 failure(s)

**Comment by vlasenko** [comment]
@drockyy It might be due to high load on CPU at the time you run testts or due to slow computer, you might try to increase timeout here (parameter -t):
https://github.com/sysgears/apollo-universal-starter-kit/blob/47bae4e53592a69ea6738fbc2b88a3746234c1fe/packages/server/package.json#L15

**Comment by drockyy** [comment]
@vlasenko I have increased the timeout by 10, but it still doesnt't work. After them, I have tried this on another machine with more ressources, and it works.
